# coding: utf-8

# flake8: noqa
"""
    Beckn Protocol Registry Infrastructure API

    This document contains the API specification for the Registry infrastructure of a beckn-enabled network. The Registry API forms the trust layer of beckn protocol. When implemented, they enable creation of an infrastructure that allow trusted transactions between network participants to take place by means of digital signature authentication. The core infrastructure is called the Network Registry or simply, Registry. Any network participant that is listed on the registry can be assumed to have successfully passed the certfication and compliance process of the network, and hence be trusted to transact with.

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from registry.models.circle import Circle
from registry.models.city import City
from registry.models.country import Country
from registry.models.descriptor import Descriptor
from registry.models.descriptor_additional_desc import DescriptorAdditionalDesc
from registry.models.image import Image
from registry.models.inline_object import InlineObject
from registry.models.inline_object1 import InlineObject1
from registry.models.location import Location
from registry.models.media_file import MediaFile
from registry.models.on_subscribe import OnSubscribe
from registry.models.scalar import Scalar
from registry.models.scalar_range import ScalarRange
from registry.models.state import State
from registry.models.subscribe import Subscribe
from registry.models.subscriber import Subscriber
from registry.models.subscription import Subscription
