# coding: utf-8

"""
    Beckn Protocol Meta API

    This document contains all the meta API endpoints that are implemented by the network participants. The information returned from these endpoints typically contain cacheable information.

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from meta.models.rating_category import RatingCategory

class RatingCategoriesMessage(BaseModel):
    """
    RatingCategoriesMessage
    """
    rating_categories: Optional[conlist(RatingCategory)] = None
    __properties = ["rating_categories"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RatingCategoriesMessage:
        """Create an instance of RatingCategoriesMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RatingCategoriesMessage:
        """Create an instance of RatingCategoriesMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RatingCategoriesMessage.parse_obj(obj)

        _obj = RatingCategoriesMessage.parse_obj({
            "rating_categories": obj.get("rating_categories")
        })
        return _obj


