[project]
name = "beckn-python"
version = "1.0.0"
description = "Python SDK for Beckn"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic[email]>=2.10.3",
    "requests>=2.32.3",
]
