# coding: utf-8

"""
    Beckn Protocol Core

    Beckn Core Transaction API specification

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr, validator

class DescriptorAdditionalDesc(BaseModel):
    """
    DescriptorAdditionalDesc
    """
    url: Optional[StrictStr] = None
    content_type: Optional[StrictStr] = None
    __properties = ["url", "content_type"]

    @validator('content_type')
    def content_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('text/plain', 'text/html', 'application/json',):
            raise ValueError("must be one of enum values ('text/plain', 'text/html', 'application/json')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DescriptorAdditionalDesc:
        """Create an instance of DescriptorAdditionalDesc from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DescriptorAdditionalDesc:
        """Create an instance of DescriptorAdditionalDesc from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DescriptorAdditionalDesc.parse_obj(obj)

        _obj = DescriptorAdditionalDesc.parse_obj({
            "url": obj.get("url"),
            "content_type": obj.get("content_type")
        })
        return _obj


