# coding: utf-8

"""
    Beckn Protocol Core

    Beckn Core Transaction API specification

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class Support(BaseModel):
    """
    Details of customer support  # noqa: E501
    """
    ref_id: Optional[StrictStr] = None
    callback_phone: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    __properties = ["ref_id", "callback_phone", "phone", "email", "url"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Support:
        """Create an instance of Support from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Support:
        """Create an instance of Support from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Support.parse_obj(obj)

        _obj = Support.parse_obj({
            "ref_id": obj.get("ref_id"),
            "callback_phone": obj.get("callback_phone"),
            "phone": obj.get("phone"),
            "email": obj.get("email"),
            "url": obj.get("url")
        })
        return _obj


