# coding: utf-8

"""
    Beckn Protocol Core

    Beckn Core Transaction API specification

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from transaction.models.x_input import XInput

class OnRatingMessage(BaseModel):
    """
    OnRatingMessage
    """
    feedback_form: Optional[XInput] = Field(default=None, description="A feedback form to allow the user to provide additional information on the rating provided")
    __properties = ["feedback_form"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OnRatingMessage:
        """Create an instance of OnRatingMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of feedback_form
        if self.feedback_form:
            _dict['feedback_form'] = self.feedback_form.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OnRatingMessage:
        """Create an instance of OnRatingMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OnRatingMessage.parse_obj(obj)

        _obj = OnRatingMessage.parse_obj({
            "feedback_form": XInput.from_dict(obj.get("feedback_form")) if obj.get("feedback_form") is not None else None
        })
        return _obj


