# coding: utf-8

"""
    Beckn Protocol Core

    Beckn Core Transaction API specification

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, conlist
from transaction.models.rating import Rating

class Rating2Message(BaseModel):
    """
    Rating2Message
    """
    ratings: Optional[conlist(Rating)] = None
    __properties = ["ratings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Rating2Message:
        """Create an instance of Rating2Message from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in ratings (list)
        _items = []
        if self.ratings:
            for _item in self.ratings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ratings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Rating2Message:
        """Create an instance of Rating2Message from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Rating2Message.parse_obj(obj)

        _obj = Rating2Message.parse_obj({
            "ratings": [Rating.from_dict(_item) for _item in obj.get("ratings")] if obj.get("ratings") is not None else None
        })
        return _obj


